### ISSUE TITLE
Minio server config is no longer at ~/.minio/config.json

### ISSUE THREAD

**Issue by tobiasjpark** [harshavardhana/minio-lambda#7]
After running `NODE_ENV=webhook node thumbnail-webhook.js` per [this tutorial](https://blog.minio.io/introducing-webhooks-for-minio-e2c3ad26deb2), the output says:

`Please update minio server config ~/.minio/config.json to enable webhook notification target.`

However, the Minio server configuration file is no longer stored at `~/.minio/config`, as explained [here](https://docs.min.io/docs/minio-server-configuration-guide.html). 

Could the instructions in the output be modified to account for the newer way that configuration is handled in Minio?

**Comment by harshavardhana** [comment]
Thanks feel free to send a PR to update the document @kd2eom
